<?php
/**
 * ============================================
 * DATABASE CONFIGURATION
 * ============================================
 * This file is auto-generated by the installer.
 * Do NOT commit this file to version control.
 * Copy this as database.php and fill in your credentials.
 */

define('DB_HOST', 'localhost');
define('DB_NAME', 'your_database_name');
define('DB_USER', 'your_database_user');
define('DB_PASS', 'your_database_password');
define('DB_CHARSET', 'utf8mb4');

// Site configuration
define('SITE_NAME', 'Mi Sitio Web');
// SITE_URL is auto-detected from the current domain
// This allows seamless domain changes in Hostinger
$_protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
define('SITE_URL', $_protocol . '://' . $_SERVER['HTTP_HOST']);
define('ADMIN_EMAIL', 'admin@tusitio.com');

// Security
define('CSRF_SECRET', 'CHANGE_THIS_TO_A_RANDOM_STRING');
define('SESSION_LIFETIME', 3600); // 1 hour in seconds
