<?php
/**
 * ============================================
 * WebCreator - INSTALLER
 * ============================================
 * Visit this file once after uploading to Hostinger.
 * It will configure the database and create the admin user.
 * After installation, this file self-locks for security.
 */

// Check if already installed
$lockFile = __DIR__ . '/.installed.lock';
$configFile = __DIR__ . '/../config/database.php';

if (file_exists($lockFile)) {
    die('
    <!DOCTYPE html><html><head><meta charset="UTF-8"><title>Ya instalado</title>
    <style>body{font-family:system-ui;display:flex;justify-content:center;align-items:center;min-height:100vh;margin:0;background:#0f172a;color:#e2e8f0;}
    .box{background:#1e293b;padding:3rem;border-radius:1rem;text-align:center;max-width:500px;border:1px solid #334155;}
    h1{color:#f87171;}a{color:#60a5fa;}</style></head>
    <body><div class="box"><h1>⚠️ Sistema ya instalado</h1><p>Si necesitas reinstalar, elimina el archivo <code>install/.installed.lock</code> y <code>config/database.php</code></p>
    <p><a href="../admin/">Ir al panel de administración →</a></p></div></body></html>');
}

$step = isset($_POST['step']) ? (int)$_POST['step'] : 1;
$errors = [];
$success = false;

// ============================================
// STEP 2: Process installation
// ============================================
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step === 2) {
    $dbHost = trim($_POST['db_host'] ?? '');
    $dbName = trim($_POST['db_name'] ?? '');
    $dbUser = trim($_POST['db_user'] ?? '');
    $dbPass = $_POST['db_pass'] ?? '';
    $siteName = trim($_POST['site_name'] ?? 'Mi Sitio Web');
    $siteUrl = trim($_POST['site_url'] ?? '');
    $adminUser = trim($_POST['admin_user'] ?? '');
    $adminEmail = trim($_POST['admin_email'] ?? '');
    $adminPass = $_POST['admin_pass'] ?? '';
    $adminPassConfirm = $_POST['admin_pass_confirm'] ?? '';

    // Validate inputs
    if (empty($dbHost)) $errors[] = 'El host de la base de datos es requerido.';
    if (empty($dbName)) $errors[] = 'El nombre de la base de datos es requerido.';
    if (empty($dbUser)) $errors[] = 'El usuario de la base de datos es requerido.';
    if (empty($adminUser)) $errors[] = 'El nombre de usuario admin es requerido.';
    if (empty($adminEmail) || !filter_var($adminEmail, FILTER_VALIDATE_EMAIL)) $errors[] = 'Email de administrador inválido.';
    if (strlen($adminPass) < 8) $errors[] = 'La contraseña debe tener al menos 8 caracteres.';
    if ($adminPass !== $adminPassConfirm) $errors[] = 'Las contraseñas no coinciden.';

    if (empty($errors)) {
        // Test database connection
        try {
            $pdo = new PDO(
                "mysql:host={$dbHost};charset=utf8mb4",
                $dbUser,
                $dbPass,
                [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                    PDO::ATTR_EMULATE_PREPARES => false
                ]
            );

            // Create database if it doesn't exist
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$dbName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $pdo->exec("USE `{$dbName}`");

            // Execute schema
            $schema = file_get_contents(__DIR__ . '/schema.sql');
            $pdo->exec($schema);

            // Create admin user
            $hashedPassword = password_hash($adminPass, PASSWORD_BCRYPT, ['cost' => 12]);
            $stmt = $pdo->prepare("INSERT INTO `users` (`username`, `email`, `password`, `full_name`, `role`, `is_active`) VALUES (?, ?, ?, ?, 'superadmin', 1)");
            $stmt->execute([$adminUser, $adminEmail, $hashedPassword, $adminUser]);

            // Update site settings
            $pdo->prepare("UPDATE `settings` SET `setting_value` = ? WHERE `setting_key` = 'site_name'")->execute([$siteName]);
            $pdo->prepare("UPDATE `settings` SET `setting_value` = ? WHERE `setting_key` = 'contact_email'")->execute([$adminEmail]);

            // Generate CSRF secret
            $csrfSecret = bin2hex(random_bytes(32));

            // Write config file
            $configContent = "<?php\n";
            $configContent .= "/**\n * Auto-generated by WebCreator Installer\n * Date: " . date('Y-m-d H:i:s') . "\n */\n\n";
            $configContent .= "define('DB_HOST', " . var_export($dbHost, true) . ");\n";
            $configContent .= "define('DB_NAME', " . var_export($dbName, true) . ");\n";
            $configContent .= "define('DB_USER', " . var_export($dbUser, true) . ");\n";
            $configContent .= "define('DB_PASS', " . var_export($dbPass, true) . ");\n";
            $configContent .= "define('DB_CHARSET', 'utf8mb4');\n\n";
            $configContent .= "define('SITE_NAME', " . var_export($siteName, true) . ");\n";
            $configContent .= "define('SITE_URL', " . var_export($siteUrl, true) . ");\n";
            $configContent .= "define('ADMIN_EMAIL', " . var_export($adminEmail, true) . ");\n\n";
            $configContent .= "define('CSRF_SECRET', " . var_export($csrfSecret, true) . ");\n";
            $configContent .= "define('SESSION_LIFETIME', 3600);\n";

            // Ensure config directory exists
            if (!is_dir(dirname($configFile))) {
                mkdir(dirname($configFile), 0755, true);
            }
            file_put_contents($configFile, $configContent);

            // Create uploads directory
            $uploadsDir = __DIR__ . '/../uploads';
            if (!is_dir($uploadsDir)) {
                mkdir($uploadsDir, 0755, true);
            }
            // Create .htaccess for uploads (only allow images)
            $uploadsHtaccess = "# Only allow image files\n";
            $uploadsHtaccess .= "<FilesMatch \"(?i)\\.(php|php3|php4|php5|phtml|pl|py|cgi|sh|bash)$\">\n";
            $uploadsHtaccess .= "    Order deny,allow\n";
            $uploadsHtaccess .= "    Deny from all\n";
            $uploadsHtaccess .= "</FilesMatch>\n\n";
            $uploadsHtaccess .= "# Disable PHP execution\n";
            $uploadsHtaccess .= "php_flag engine off\n";
            file_put_contents($uploadsDir . '/.htaccess', $uploadsHtaccess);

            // Create lock file
            file_put_contents($lockFile, 'Installed on: ' . date('Y-m-d H:i:s') . "\nBy: {$adminEmail}");

            $success = true;

        } catch (PDOException $e) {
            $errors[] = 'Error de conexión a la base de datos: ' . $e->getMessage();
        } catch (Exception $e) {
            $errors[] = 'Error durante la instalación: ' . $e->getMessage();
        }
    }

    if (!empty($errors)) {
        $step = 2; // Stay on form with errors
    }
}
?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instalador - WebCreator</title>
    <style>
        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

        :root {
            --bg-primary: #0f172a;
            --bg-secondary: #1e293b;
            --bg-card: #1e293b;
            --border: #334155;
            --text-primary: #f1f5f9;
            --text-secondary: #94a3b8;
            --accent: #3b82f6;
            --accent-hover: #2563eb;
            --success: #22c55e;
            --danger: #ef4444;
            --warning: #f59e0b;
            --radius: 0.75rem;
        }

        body {
            font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
            background: var(--bg-primary);
            color: var(--text-primary);
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 2rem;
            background-image: 
                radial-gradient(ellipse at 20% 50%, rgba(59, 130, 246, 0.08) 0%, transparent 50%),
                radial-gradient(ellipse at 80% 20%, rgba(139, 92, 246, 0.06) 0%, transparent 50%);
        }

        .installer {
            width: 100%;
            max-width: 640px;
            background: var(--bg-card);
            border: 1px solid var(--border);
            border-radius: 1.5rem;
            overflow: hidden;
            box-shadow: 0 25px 50px -12px rgba(0,0,0,0.5);
        }

        .installer-header {
            padding: 2.5rem 2.5rem 1.5rem;
            text-align: center;
            border-bottom: 1px solid var(--border);
            background: linear-gradient(135deg, rgba(59,130,246,0.1), rgba(139,92,246,0.1));
        }

        .installer-header .logo {
            font-size: 2.5rem;
            margin-bottom: 0.5rem;
        }

        .installer-header h1 {
            font-size: 1.5rem;
            font-weight: 700;
            margin-bottom: 0.25rem;
        }

        .installer-header p {
            color: var(--text-secondary);
            font-size: 0.9rem;
        }

        .installer-body {
            padding: 2rem 2.5rem 2.5rem;
        }

        .step-indicator {
            display: flex;
            justify-content: center;
            gap: 0.5rem;
            margin-bottom: 2rem;
        }

        .step-dot {
            width: 10px;
            height: 10px;
            border-radius: 50%;
            background: var(--border);
            transition: all 0.3s;
        }

        .step-dot.active {
            background: var(--accent);
            box-shadow: 0 0 10px rgba(59,130,246,0.5);
        }

        .step-dot.done {
            background: var(--success);
        }

        .section-title {
            font-size: 0.85rem;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: var(--accent);
            margin-bottom: 1rem;
            margin-top: 1.5rem;
        }

        .section-title:first-of-type { margin-top: 0; }

        .form-group {
            margin-bottom: 1rem;
        }

        .form-group label {
            display: block;
            font-size: 0.85rem;
            font-weight: 500;
            color: var(--text-secondary);
            margin-bottom: 0.35rem;
        }

        .form-group input {
            width: 100%;
            padding: 0.7rem 1rem;
            background: var(--bg-primary);
            border: 1px solid var(--border);
            border-radius: var(--radius);
            color: var(--text-primary);
            font-size: 0.95rem;
            transition: border-color 0.2s, box-shadow 0.2s;
        }

        .form-group input:focus {
            outline: none;
            border-color: var(--accent);
            box-shadow: 0 0 0 3px rgba(59,130,246,0.15);
        }

        .form-group input::placeholder {
            color: #475569;
        }

        .form-row {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 1rem;
        }

        .errors {
            background: rgba(239,68,68,0.1);
            border: 1px solid rgba(239,68,68,0.3);
            border-radius: var(--radius);
            padding: 1rem;
            margin-bottom: 1.5rem;
        }

        .errors ul {
            list-style: none;
            padding: 0;
            margin: 0;
        }

        .errors li {
            color: #fca5a5;
            font-size: 0.85rem;
            padding: 0.2rem 0;
        }

        .errors li::before {
            content: '✕ ';
            color: var(--danger);
        }

        .btn {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            gap: 0.5rem;
            width: 100%;
            padding: 0.85rem 1.5rem;
            border: none;
            border-radius: var(--radius);
            font-size: 1rem;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.2s;
        }

        .btn-primary {
            background: var(--accent);
            color: white;
        }

        .btn-primary:hover {
            background: var(--accent-hover);
            transform: translateY(-1px);
            box-shadow: 0 4px 15px rgba(59,130,246,0.4);
        }

        .btn-success {
            background: var(--success);
            color: white;
        }

        .btn-success:hover {
            background: #16a34a;
        }

        /* Success screen */
        .success-screen {
            text-align: center;
            padding: 1rem 0;
        }

        .success-icon {
            font-size: 4rem;
            margin-bottom: 1rem;
            animation: bounceIn 0.6s ease;
        }

        @keyframes bounceIn {
            0% { transform: scale(0); } 
            60% { transform: scale(1.2); }
            100% { transform: scale(1); }
        }

        .success-screen h2 {
            font-size: 1.5rem;
            margin-bottom: 0.75rem;
            color: var(--success);
        }

        .success-screen p {
            color: var(--text-secondary);
            font-size: 0.9rem;
            margin-bottom: 0.5rem;
        }

        .credentials-box {
            background: var(--bg-primary);
            border: 1px solid var(--border);
            border-radius: var(--radius);
            padding: 1rem;
            margin: 1.5rem 0;
            text-align: left;
        }

        .credentials-box p { margin: 0.25rem 0; font-size: 0.85rem; }
        .credentials-box strong { color: var(--accent); }

        .security-note {
            background: rgba(245,158,11,0.1);
            border: 1px solid rgba(245,158,11,0.3);
            border-radius: var(--radius);
            padding: 0.75rem 1rem;
            font-size: 0.8rem;
            color: var(--warning);
            margin: 1rem 0;
        }

        /* Welcome screen (Step 1) */
        .welcome-features {
            list-style: none;
            padding: 0;
            margin: 1.5rem 0;
        }

        .welcome-features li {
            padding: 0.6rem 0;
            font-size: 0.9rem;
            color: var(--text-secondary);
            display: flex;
            align-items: center;
            gap: 0.75rem;
        }

        .welcome-features li .icon {
            font-size: 1.1rem;
        }

        .requirements {
            background: var(--bg-primary);
            border-radius: var(--radius);
            padding: 1rem;
            margin-bottom: 1.5rem;
        }

        .requirements h3 {
            font-size: 0.85rem;
            color: var(--text-primary);
            margin-bottom: 0.75rem;
        }

        .req-item {
            display: flex;
            align-items: center;
            gap: 0.5rem;
            font-size: 0.85rem;
            padding: 0.3rem 0;
            color: var(--text-secondary);
        }

        .req-item .check { color: var(--success); }
        .req-item .cross { color: var(--danger); }
    </style>
</head>
<body>
    <div class="installer">
        <div class="installer-header">
            <div class="logo">🚀</div>
            <h1>WebCreator Installer</h1>
            <p>Configuración inicial del sistema</p>
        </div>

        <div class="installer-body">
            <div class="step-indicator">
                <div class="step-dot <?= $step >= 1 ? ($success ? 'done' : 'active') : '' ?>"></div>
                <div class="step-dot <?= $step >= 2 ? ($success ? 'done' : 'active') : '' ?>"></div>
                <div class="step-dot <?= $success ? 'done' : '' ?>"></div>
            </div>

            <?php if ($success): ?>
                <!-- ============================================ -->
                <!-- SUCCESS SCREEN -->
                <!-- ============================================ -->
                <div class="success-screen">
                    <div class="success-icon">✅</div>
                    <h2>¡Instalación Completada!</h2>
                    <p>El sistema se ha configurado correctamente.</p>

                    <div class="credentials-box">
                        <p><strong>Panel Admin:</strong> <a href="../admin/" style="color:#60a5fa;"><?= htmlspecialchars($siteUrl) ?>/admin/</a></p>
                        <p><strong>Usuario:</strong> <?= htmlspecialchars($adminUser) ?></p>
                        <p><strong>Email:</strong> <?= htmlspecialchars($adminEmail) ?></p>
                    </div>

                    <div class="security-note">
                        ⚠️ El instalador ha sido bloqueado automáticamente. Guarda tus credenciales en un lugar seguro.
                    </div>

                    <a href="../admin/" class="btn btn-success">Ir al Panel de Administración →</a>
                </div>

            <?php elseif ($step === 1): ?>
                <!-- ============================================ -->
                <!-- STEP 1: WELCOME -->
                <!-- ============================================ -->
                <h2 style="font-size:1.2rem; margin-bottom:0.5rem;">Bienvenido al instalador</h2>
                <p style="color:var(--text-secondary); font-size:0.9rem;">Este asistente configurará tu sitio web en pocos pasos.</p>

                <ul class="welcome-features">
                    <li><span class="icon">📦</span> Conexión a base de datos MySQL</li>
                    <li><span class="icon">🗄️</span> Creación automática de tablas</li>
                    <li><span class="icon">👤</span> Cuenta de administrador</li>
                    <li><span class="icon">🔒</span> Configuración de seguridad</li>
                    <li><span class="icon">📁</span> Directorio de uploads</li>
                </ul>

                <div class="requirements">
                    <h3>Requisitos del sistema:</h3>
                    <div class="req-item">
                        <span class="<?= version_compare(PHP_VERSION, '7.4', '>=') ? 'check' : 'cross' ?>">
                            <?= version_compare(PHP_VERSION, '7.4', '>=') ? '✓' : '✕' ?>
                        </span>
                        PHP 7.4+ (actual: <?= PHP_VERSION ?>)
                    </div>
                    <div class="req-item">
                        <span class="<?= extension_loaded('pdo_mysql') ? 'check' : 'cross' ?>">
                            <?= extension_loaded('pdo_mysql') ? '✓' : '✕' ?>
                        </span>
                        Extensión PDO MySQL
                    </div>
                    <div class="req-item">
                        <span class="<?= extension_loaded('json') ? 'check' : 'cross' ?>">
                            <?= extension_loaded('json') ? '✓' : '✕' ?>
                        </span>
                        Extensión JSON
                    </div>
                    <div class="req-item">
                        <span class="<?= is_writable(__DIR__ . '/../config/') ? 'check' : 'cross' ?>">
                            <?= is_writable(__DIR__ . '/../config/') ? '✓' : '✕' ?>
                        </span>
                        Directorio /config/ escribible
                    </div>
                </div>

                <form method="POST">
                    <input type="hidden" name="step" value="2">
                    <button type="submit" class="btn btn-primary">Comenzar Instalación →</button>
                </form>

            <?php else: ?>
                <!-- ============================================ -->
                <!-- STEP 2: CONFIGURATION FORM -->
                <!-- ============================================ -->

                <?php if (!empty($errors)): ?>
                    <div class="errors">
                        <ul>
                            <?php foreach ($errors as $error): ?>
                                <li><?= htmlspecialchars($error) ?></li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif; ?>

                <form method="POST">
                    <input type="hidden" name="step" value="2">

                    <div class="section-title">🗄️ Base de Datos MySQL</div>

                    <div class="form-row">
                        <div class="form-group">
                            <label for="db_host">Host</label>
                            <input type="text" id="db_host" name="db_host" value="<?= htmlspecialchars($_POST['db_host'] ?? 'localhost') ?>" placeholder="localhost" required>
                        </div>
                        <div class="form-group">
                            <label for="db_name">Nombre de la BD</label>
                            <input type="text" id="db_name" name="db_name" value="<?= htmlspecialchars($_POST['db_name'] ?? '') ?>" placeholder="mi_base_datos" required>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group">
                            <label for="db_user">Usuario BD</label>
                            <input type="text" id="db_user" name="db_user" value="<?= htmlspecialchars($_POST['db_user'] ?? '') ?>" placeholder="u_usuario" required>
                        </div>
                        <div class="form-group">
                            <label for="db_pass">Contraseña BD</label>
                            <input type="password" id="db_pass" name="db_pass" value="" placeholder="••••••••">
                        </div>
                    </div>

                    <div class="section-title">🌐 Configuración del Sitio</div>

                    <div class="form-row">
                        <div class="form-group">
                            <label for="site_name">Nombre del Sitio</label>
                            <input type="text" id="site_name" name="site_name" value="<?= htmlspecialchars($_POST['site_name'] ?? 'Mi Sitio Web') ?>" placeholder="Mi Sitio Web" required>
                        </div>
                        <div class="form-group">
                            <label for="site_url">URL del Sitio</label>
                            <input type="url" id="site_url" name="site_url" value="<?= htmlspecialchars($_POST['site_url'] ?? '') ?>" placeholder="https://tusitio.com" required>
                        </div>
                    </div>

                    <div class="section-title">👤 Cuenta de Administrador</div>

                    <div class="form-row">
                        <div class="form-group">
                            <label for="admin_user">Nombre de Usuario</label>
                            <input type="text" id="admin_user" name="admin_user" value="<?= htmlspecialchars($_POST['admin_user'] ?? 'admin') ?>" placeholder="admin" required>
                        </div>
                        <div class="form-group">
                            <label for="admin_email">Email</label>
                            <input type="email" id="admin_email" name="admin_email" value="<?= htmlspecialchars($_POST['admin_email'] ?? '') ?>" placeholder="admin@tusitio.com" required>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group">
                            <label for="admin_pass">Contraseña</label>
                            <input type="password" id="admin_pass" name="admin_pass" placeholder="Mínimo 8 caracteres" required minlength="8">
                        </div>
                        <div class="form-group">
                            <label for="admin_pass_confirm">Confirmar Contraseña</label>
                            <input type="password" id="admin_pass_confirm" name="admin_pass_confirm" placeholder="Repetir contraseña" required minlength="8">
                        </div>
                    </div>

                    <div style="margin-top: 1.5rem;">
                        <button type="submit" class="btn btn-primary">⚡ Instalar Ahora</button>
                    </div>
                </form>
            <?php endif; ?>
        </div>
    </div>
</body>
</html>
